  // ====== RNN (8) ======
  {
    id: 'tpl-lstm-base',
    name: 'LSTM Base',
    family: 'rnn',
    description: '2-layer BiLSTM with 512 hidden units, 100k vocab embedding, and 0.3 dropout — ~66M params',
    tags: ['bilstm', 'classification', 'language-modeling'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Input', x: 50, y: 140, params: { dims: [1, 128] } },
      { id: 'n2', type: 'embedding', name: 'Embedding', x: 220, y: 140, params: { vocab_size: 100000, embedding_dim: 512, padding_idx: 0 } },
      { id: 'n3', type: 'bilstm', name: 'BiLSTM-1', x: 420, y: 140, params: { hidden_size: 512, num_layers: 1, bidirectional: true, batch_first: true } },
      { id: 'n4', type: 'dropout', name: 'Dropout-1', x: 620, y: 140, params: { p: 0.3, inplace: false } },
      { id: 'n5', type: 'bilstm', name: 'BiLSTM-2', x: 820, y: 140, params: { hidden_size: 256, num_layers: 1, bidirectional: true, batch_first: true } },
      { id: 'n6', type: 'dropout', name: 'Dropout-2', x: 1020, y: 140, params: { p: 0.3, inplace: false } },
      { id: 'n7', type: 'linear', name: 'Classifier', x: 1220, y: 140, params: { in_features: 512, out_features: 100000, bias: true } },
      { id: 'n8', type: 'output', name: 'Output', x: 1420, y: 140, params: { dims: [1, 100000] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-gru-base',
    name: 'GRU Base',
    family: 'rnn',
    description: '2-layer BiGRU with 512 hidden units and 100k vocab embedding — ~63M params',
    tags: ['bigru', 'classification', 'language-modeling'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Input', x: 50, y: 140, params: { dims: [1, 128] } },
      { id: 'n2', type: 'embedding', name: 'Embedding', x: 220, y: 140, params: { vocab_size: 100000, embedding_dim: 512, padding_idx: 0 } },
      { id: 'n3', type: 'bigru', name: 'BiGRU-1', x: 420, y: 140, params: { hidden_size: 512, num_layers: 1, bidirectional: true, batch_first: true } },
      { id: 'n4', type: 'dropout', name: 'Dropout', x: 620, y: 140, params: { p: 0.3, inplace: false } },
      { id: 'n5', type: 'bigru', name: 'BiGRU-2', x: 820, y: 140, params: { hidden_size: 256, num_layers: 1, bidirectional: true, batch_first: true } },
      { id: 'n6', type: 'linear', name: 'Classifier', x: 1020, y: 140, params: { in_features: 512, out_features: 100000, bias: true } },
      { id: 'n7', type: 'output', name: 'Output', x: 1220, y: 140, params: { dims: [1, 100000] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-lstm-seq2seq',
    name: 'LSTM Seq2Seq',
    family: 'rnn',
    description: '4-layer LSTM encoder-decoder with additive attention, 512 hidden, 300d embeddings — ~38M params',
    tags: ['seq2seq', 'attention', 'translation'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Source Input', x: 50, y: 140, params: { dims: [1, 64] } },
      { id: 'n2', type: 'embedding', name: 'Embedding', x: 220, y: 140, params: { vocab_size: 50000, embedding_dim: 300, padding_idx: 0 } },
      { id: 'n3', type: 'lstm_cell', name: 'Encoder-L1', x: 420, y: 80, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n4', type: 'lstm_cell', name: 'Encoder-L2', x: 420, y: 200, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n5', type: 'lstm_cell', name: 'Encoder-L3', x: 620, y: 80, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n6', type: 'lstm_cell', name: 'Encoder-L4', x: 620, y: 200, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n7', type: 'attention', name: 'Bahdanau Attn', x: 820, y: 140, params: { score: 'add', hidden_dim: 512, normalize: true } },
      { id: 'n8', type: 'lstm_cell', name: 'Decoder-L1', x: 1020, y: 80, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n9', type: 'lstm_cell', name: 'Decoder-L2', x: 1020, y: 200, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n10', type: 'lstm_cell', name: 'Decoder-L3', x: 1220, y: 80, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n11', type: 'lstm_cell', name: 'Decoder-L4', x: 1220, y: 200, params: { hidden_size: 512, num_layers: 1, batch_first: true } },
      { id: 'n12', type: 'linear', name: 'Projection', x: 1420, y: 140, params: { in_features: 512, out_features: 50000, bias: true } },
      { id: 'n13', type: 'output', name: 'Target Output', x: 1620, y: 140, params: { dims: [1, 50000] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
      { id: 'c9', from: 'n9', to: 'n10' },
      { id: 'c10', from: 'n10', to: 'n11' },
      { id: 'c11', from: 'n11', to: 'n12' },
      { id: 'c12', from: 'n12', to: 'n13' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-gru-seq2seq',
    name: 'GRU Seq2Seq',
    family: 'rnn',
    description: 'GRU encoder-decoder with 512 hidden units and 300d embeddings — ~23M params',
    tags: ['seq2seq', 'translation', 'gru'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Source Input', x: 50, y: 140, params: { dims: [1, 64] } },
      { id: 'n2', type: 'embedding', name: 'Embedding', x: 220, y: 140, params: { vocab_size: 50000, embedding_dim: 300, padding_idx: 0 } },
      { id: 'n3', type: 'gru_cell', name: 'Encoder GRU', x: 420, y: 140, params: { hidden_size: 512, num_layers: 2, bidirectional: true, batch_first: true } },
      { id: 'n4', type: 'attention', name: 'Luong Attn', x: 620, y: 140, params: { score: 'general', hidden_dim: 1024, normalize: false } },
      { id: 'n5', type: 'gru_cell', name: 'Decoder GRU', x: 820, y: 140, params: { hidden_size: 512, num_layers: 2, bidirectional: false, batch_first: true } },
      { id: 'n6', type: 'concat', name: 'Context Concat', x: 1020, y: 140, params: { dim: 2 } },
      { id: 'n7', type: 'linear', name: 'Projection', x: 1220, y: 140, params: { in_features: 1024, out_features: 50000, bias: true } },
      { id: 'n8', type: 'output', name: 'Target Output', x: 1420, y: 140, params: { dims: [1, 50000] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n4', to: 'n6' },
      { id: 'c7', from: 'n6', to: 'n7' },
      { id: 'c8', from: 'n7', to: 'n8' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-indrnn',
    name: 'IndRNN',
    family: 'rnn',
    description: '6-layer independently recurrent RNN with 128 hidden units and ReLU activation — ~6M params',
    tags: ['indrnn', 'deep-rnn', 'relu'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Input', x: 50, y: 140, params: { dims: [1, 128] } },
      { id: 'n2', type: 'linear', name: 'Input Projection', x: 220, y: 140, params: { in_features: 128, out_features: 128, bias: false } },
      { id: 'n3', type: 'indrnn_cell', name: 'IndRNN-L1', x: 400, y: 80, params: { hidden_size: 128, activation: 'relu', recurrent_max: 1.0, batch_first: true } },
      { id: 'n4', type: 'indrnn_cell', name: 'IndRNN-L2', x: 400, y: 200, params: { hidden_size: 128, activation: 'relu', recurrent_max: 1.0, batch_first: true } },
      { id: 'n5', type: 'indrnn_cell', name: 'IndRNN-L3', x: 580, y: 80, params: { hidden_size: 128, activation: 'relu', recurrent_max: 1.0, batch_first: true } },
      { id: 'n6', type: 'indrnn_cell', name: 'IndRNN-L4', x: 580, y: 200, params: { hidden_size: 128, activation: 'relu', recurrent_max: 1.0, batch_first: true } },
      { id: 'n7', type: 'indrnn_cell', name: 'IndRNN-L5', x: 760, y: 80, params: { hidden_size: 128, activation: 'relu', recurrent_max: 1.0, batch_first: true } },
      { id: 'n8', type: 'indrnn_cell', name: 'IndRNN-L6', x: 760, y: 200, params: { hidden_size: 128, activation: 'relu', recurrent_max: 1.0, batch_first: true } },
      { id: 'n9', type: 'linear', name: 'Output Projection', x: 940, y: 140, params: { in_features: 128, out_features: 10, bias: true } },
      { id: 'n10', type: 'output', name: 'Output', x: 1120, y: 140, params: { dims: [1, 10] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
      { id: 'c9', from: 'n9', to: 'n10' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-phaser-lstm',
    name: 'Phased LSTM',
    family: 'rnn',
    description: '3-layer Phased LSTM with multiple timescales, 256 hidden units, learnable gate periods — ~6M params',
    tags: ['phaselstm', 'time-series', 'event-driven'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Input', x: 50, y: 140, params: { dims: [1, 128] } },
      { id: 'n2', type: 'linear', name: 'Input Projection', x: 220, y: 140, params: { in_features: 128, out_features: 256, bias: true } },
      { id: 'n3', type: 'phaselstm_cell', name: 'Phased-LSTM-L1', x: 420, y: 80, params: { hidden_size: 256, time_scales: [10, 50, 100], leak_rate: 0.001, batch_first: true } },
      { id: 'n4', type: 'phaselstm_cell', name: 'Phased-LSTM-L2', x: 420, y: 200, params: { hidden_size: 256, time_scales: [100, 500, 1000], leak_rate: 0.001, batch_first: true } },
      { id: 'n5', type: 'phaselstm_cell', name: 'Phased-LSTM-L3', x: 620, y: 140, params: { hidden_size: 256, time_scales: [1000, 5000, 10000], leak_rate: 0.001, batch_first: true } },
      { id: 'n6', type: 'dropout', name: 'Dropout', x: 820, y: 140, params: { p: 0.2, inplace: false } },
      { id: 'n7', type: 'linear', name: 'Output Layer', x: 1020, y: 140, params: { in_features: 256, out_features: 10, bias: true } },
      { id: 'n8', type: 'output', name: 'Output', x: 1220, y: 140, params: { dims: [1, 10] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-sru',
    name: 'Simple Recurrent Unit',
    family: 'rnn',
    description: '4-layer SRU with 512 hidden units and highway connections — ~13M params',
    tags: ['sru', 'fast-rnn', 'highway'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Input', x: 50, y: 140, params: { dims: [1, 128] } },
      { id: 'n2', type: 'linear', name: 'Input Projection', x: 220, y: 140, params: { in_features: 128, out_features: 512, bias: true } },
      { id: 'n3', type: 'sru_cell', name: 'SRU-L1', x: 420, y: 80, params: { hidden_size: 512, highway: true, dropout: 0.1, batch_first: true } },
      { id: 'n4', type: 'sru_cell', name: 'SRU-L2', x: 420, y: 200, params: { hidden_size: 512, highway: true, dropout: 0.1, batch_first: true } },
      { id: 'n5', type: 'sru_cell', name: 'SRU-L3', x: 620, y: 80, params: { hidden_size: 512, highway: true, dropout: 0.1, batch_first: true } },
      { id: 'n6', type: 'sru_cell', name: 'SRU-L4', x: 620, y: 200, params: { hidden_size: 512, highway: true, dropout: 0.1, batch_first: true } },
      { id: 'n7', type: 'linear', name: 'Classifier', x: 820, y: 140, params: { in_features: 512, out_features: 10000, bias: true } },
      { id: 'n8', type: 'output', name: 'Output', x: 1020, y: 140, params: { dims: [1, 10000] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-janet',
    name: 'JANET',
    family: 'rnn',
    description: '3-layer JANET with 512 hidden units, forget bias 1.0, gated recurrent — ~10M params',
    tags: ['janet', 'gated-rnn', 'forget-bias'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Input', x: 50, y: 140, params: { dims: [1, 128] } },
      { id: 'n2', type: 'embedding', name: 'Embedding', x: 220, y: 140, params: { vocab_size: 50000, embedding_dim: 256, padding_idx: 0 } },
      { id: 'n3', type: 'janet_cell', name: 'JANET-L1', x: 420, y: 80, params: { hidden_size: 512, forget_bias: 1.0, batch_first: true } },
      { id: 'n4', type: 'janet_cell', name: 'JANET-L2', x: 420, y: 200, params: { hidden_size: 512, forget_bias: 1.0, batch_first: true } },
      { id: 'n5', type: 'janet_cell', name: 'JANET-L3', x: 620, y: 140, params: { hidden_size: 512, forget_bias: 1.0, batch_first: true } },
      { id: 'n6', type: 'dropout', name: 'Dropout', x: 820, y: 140, params: { p: 0.3, inplace: false } },
      { id: 'n7', type: 'linear', name: 'Output Projection', x: 1020, y: 140, params: { in_features: 512, out_features: 50000, bias: true } },
      { id: 'n8', type: 'output', name: 'Output', x: 1220, y: 140, params: { dims: [1, 50000] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n2' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
    ],
    defaultParams: {},
  },
  // ====== DIFFUSION (8) ======
  {
    id: 'tpl-ddpm',
    name: 'DDPM',
    family: 'diffusion',
    description: 'DDPM UNet with 256 base dims, 4 resolution stages (64→128→256→512), cosine noise schedule — ~112M params',
    tags: ['ddpm', 'unet', 'markov-chain', 'gaussian-diffusion'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Noisy Image', x: 50, y: 140, params: { dims: [1, 3, 64, 64] } },
      { id: 'n2', type: 'time_embedding', name: 'Time Embed', x: 50, y: 20, params: { dim: 256, max_period: 10000 } },
      { id: 'n3', type: 'diffusion_unet', name: 'UNet-Stage-1', x: 250, y: 80, params: { channels: 64, depth: 2, resolution: 64, attention: false } },
      { id: 'n4', type: 'diffusion_unet', name: 'UNet-Stage-2', x: 250, y: 200, params: { channels: 128, depth: 2, resolution: 32, attention: false } },
      { id: 'n5', type: 'diffusion_unet', name: 'UNet-Stage-3', x: 450, y: 80, params: { channels: 256, depth: 2, resolution: 16, attention: true } },
      { id: 'n6', type: 'diffusion_unet', name: 'UNet-Stage-4', x: 450, y: 200, params: { channels: 512, depth: 2, resolution: 8, attention: true } },
      { id: 'n7', type: 'noise_schedule', name: 'Cosine Sched', x: 650, y: 140, params: { schedule: 'cosine', T: 1000, beta_min: 0.0001, beta_max: 0.02 } },
      { id: 'n8', type: 'concat', name: 'Skip Fusion', x: 850, y: 140, params: { dim: 1 } },
      { id: 'n9', type: 'output', name: 'Denoised Image', x: 1050, y: 140, params: { dims: [1, 3, 64, 64] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n3' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-ddim',
    name: 'DDIM',
    family: 'diffusion',
    description: 'DDIM with same UNet backbone as DDPM (256→512→1024→2048), deterministic sampling — ~114M params',
    tags: ['ddim', 'deterministic', 'fast-sampling', 'unet'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Noisy Image', x: 50, y: 140, params: { dims: [1, 3, 64, 64] } },
      { id: 'n2', type: 'time_embedding', name: 'Time Embed', x: 50, y: 20, params: { dim: 256, max_period: 10000 } },
      { id: 'n3', type: 'diffusion_unet', name: 'UNet-Stage-1', x: 250, y: 80, params: { channels: 64, depth: 2, resolution: 64, attention: false } },
      { id: 'n4', type: 'diffusion_unet', name: 'UNet-Stage-2', x: 250, y: 200, params: { channels: 128, depth: 2, resolution: 32, attention: false } },
      { id: 'n5', type: 'diffusion_unet', name: 'UNet-Stage-3', x: 450, y: 80, params: { channels: 256, depth: 2, resolution: 16, attention: true } },
      { id: 'n6', type: 'diffusion_unet', name: 'UNet-Stage-4', x: 450, y: 200, params: { channels: 512, depth: 2, resolution: 8, attention: true } },
      { id: 'n7', type: 'noise_schedule', name: 'DDIM Sched', x: 650, y: 140, params: { schedule: 'ddim', T: 50, eta: 0.0, beta_min: 0.0001, beta_max: 0.02 } },
      { id: 'n8', type: 'output', name: 'Denoised Image', x: 850, y: 140, params: { dims: [1, 3, 64, 64] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n3' },
      { id: 'c2', from: 'n2', to: 'n3' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-stable-diffusion-v1',
    name: 'Stable Diffusion v1.5',
    family: 'diffusion',
    description: 'SD 1.5 UNet (860M) with CLIP text encoder, 8×8 cross-attention, 512×512 output — ~1.2B total params',
    tags: ['stable-diffusion', 'ldm', 'clip', 'cross-attention'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Latent Noise', x: 50, y: 140, params: { dims: [1, 4, 64, 64] } },
      { id: 'n2', type: 'text_encoder', name: 'CLIP Text', x: 50, y: 20, params: { model: 'openai/clip-vit-large-patch14', max_length: 77, dim: 768 } },
      { id: 'n3', type: 'time_embedding', name: 'Time Embed', x: 250, y: 20, params: { dim: 1280, max_period: 10000 } },
      { id: 'n4', type: 'diffusion_unet', name: 'UNet-Input', x: 270, y: 140, params: { channels: 320, depth: 2, resolution: 64, attention: false } },
      { id: 'n5', type: 'diffusion_unet', name: 'UNet-Mid', x: 470, y: 140, params: { channels: 640, depth: 2, resolution: 32, attention: false } },
      { id: 'n6', type: 'cross_attention', name: 'Cross-Attn-8x8', x: 670, y: 80, params: { resolution: 8, heads: 8, d_head: 64, context_dim: 768 } },
      { id: 'n7', type: 'diffusion_unet', name: 'UNet-Out', x: 670, y: 200, params: { channels: 1280, depth: 2, resolution: 8, attention: true } },
      { id: 'n8', type: 'noise_schedule', name: 'Noise Sched', x: 870, y: 140, params: { schedule: 'scaled_linear', T: 1000, beta_start: 0.00085, beta_end: 0.012 } },
      { id: 'n9', type: 'layer_stack', name: 'Output Stack', x: 1070, y: 140, params: { channels: [1280, 640, 320, 4], use_conv: true } },
      { id: 'n10', type: 'output', name: 'Denoised Latent', x: 1270, y: 140, params: { dims: [1, 4, 64, 64] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n4' },
      { id: 'c2', from: 'n2', to: 'n6' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
      { id: 'c9', from: 'n9', to: 'n10' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    family: 'diffusion',
    description: 'SDXL UNet (2.6B) with dual CLIP/OpenCLIP text encoders, 1024×1024 output — ~3.5B total params',
    tags: ['stable-diffusion', 'sdxl', 'dual-encoder', 'high-res'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Latent Noise', x: 50, y: 140, params: { dims: [1, 4, 128, 128] } },
      { id: 'n2', type: 'text_encoder', name: 'CLIP-L/14', x: 50, y: 20, params: { model: 'openai/clip-vit-large-patch14', max_length: 77, dim: 768 } },
      { id: 'n3', type: 'text_encoder', name: 'OpenCLIP-bigG', x: 250, y: 20, params: { model: 'laion/CLIP-ViT-bigG-14-laion2B-39B-b160k', max_length: 77, dim: 1280 } },
      { id: 'n4', type: 'time_embedding', name: 'Time Embed', x: 470, y: 20, params: { dim: 2560, max_period: 10000 } },
      { id: 'n5', type: 'diffusion_unet', name: 'UNet-L1', x: 270, y: 140, params: { channels: 640, depth: 2, resolution: 128, attention: false } },
      { id: 'n6', type: 'diffusion_unet', name: 'UNet-L2', x: 470, y: 140, params: { channels: 1280, depth: 2, resolution: 64, attention: true } },
      { id: 'n7', type: 'cross_attention', name: 'Dual Cross-Attn', x: 670, y: 140, params: { resolution: 8, heads: 16, d_head: 80, context_dim: [768, 1280] } },
      { id: 'n8', type: 'diffusion_unet', name: 'UNet-L3', x: 870, y: 140, params: { channels: 2560, depth: 2, resolution: 16, attention: true } },
      { id: 'n9', type: 'noise_schedule', name: 'Noise Sched', x: 1070, y: 140, params: { schedule: 'scaled_linear', T: 1000, beta_start: 0.00085, beta_end: 0.012 } },
      { id: 'n10', type: 'layer_stack', name: 'Decoder Stack', x: 1270, y: 140, params: { channels: [2560, 1280, 640, 4], use_conv: true } },
      { id: 'n11', type: 'output', name: 'Denoised Latent', x: 1470, y: 140, params: { dims: [1, 4, 128, 128] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n5' },
      { id: 'c2', from: 'n2', to: 'n7' },
      { id: 'c3', from: 'n3', to: 'n7' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
      { id: 'c9', from: 'n9', to: 'n10' },
      { id: 'c10', from: 'n10', to: 'n11' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-imagen',
    name: 'Imagen',
    family: 'diffusion',
    description: 'Google Imagen 256×256 with 400M text-to-image UNet, T5-XXL encoder (11B), efficient UNet with dynamic conditioning — ~11.4B total params',
    tags: ['imagen', 't5', 'text-to-image', 'efficient-unet'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Noise 256x256', x: 50, y: 140, params: { dims: [1, 3, 256, 256] } },
      { id: 'n2', type: 'text_encoder', name: 'T5-XXL', x: 50, y: 20, params: { model: 't5-11b', max_length: 128, dim: 4096, encoder_only: true } },
      { id: 'n3', type: 'time_embedding', name: 'Time Embed', x: 290, y: 20, params: { dim: 1024, max_period: 10000 } },
      { id: 'n4', type: 'diffusion_unet', name: 'Efficient UNet-Base', x: 270, y: 140, params: { channels: 128, depth: 3, resolution: 256, efficient: true } },
      { id: 'n5', type: 'cross_attention', name: 'T5 Cross-Attn', x: 490, y: 140, params: { resolution: 16, heads: 16, d_head: 64, context_dim: 4096 } },
      { id: 'n6', type: 'diffusion_unet', name: 'Efficient UNet-Mid', x: 710, y: 140, params: { channels: 256, depth: 3, resolution: 64, efficient: true } },
      { id: 'n7', type: 'diffusion_unet', name: 'Efficient UNet-Deep', x: 930, y: 140, params: { channels: 512, depth: 3, resolution: 16, efficient: true } },
      { id: 'n8', type: 'noise_schedule', name: 'Dynamic Sched', x: 1150, y: 140, params: { schedule: 'dynamic', T: 1000, beta_min: 0.0001, beta_max: 0.02 } },
      { id: 'n9', type: 'output', name: 'Generated Image', x: 1350, y: 140, params: { dims: [1, 3, 256, 256] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n4' },
      { id: 'c2', from: 'n2', to: 'n5' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-dalle-3',
    name: 'DALL·E 3',
    family: 'diffusion',
    description: 'DALL·E 3 decoder (3.5B params), transformer-based diffusion with joint text-image attention blocks — ~3.5B total params',
    tags: ['dalle3', 'transformer', 'decoder-only', 'joint-attention'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Latent Tokens', x: 50, y: 140, params: { dims: [1, 1024, 256] } },
      { id: 'n2', type: 'text_encoder', name: 'T5-XXL Enc', x: 50, y: 20, params: { model: 't5-11b', max_length: 256, dim: 4096, encoder_only: true } },
      { id: 'n3', type: 'time_embedding', name: 'Time Embed', x: 290, y: 20, params: { dim: 2048, max_period: 10000 } },
      { id: 'n4', type: 'layer_stack', name: 'Joint Attn Blk ×16', x: 300, y: 140, params: { num_layers: 16, hidden_dim: 256, heads: 16, d_head: 64, context_dim: 4096 } },
      { id: 'n5', type: 'cross_attention', name: 'Text Condition', x: 530, y: 140, params: { resolution: 32, heads: 16, d_head: 64, context_dim: 4096 } },
      { id: 'n6', type: 'layer_stack', name: 'Decoder Blk ×8', x: 760, y: 140, params: { num_layers: 8, hidden_dim: 512, heads: 16, d_head: 64, use_causal_mask: true } },
      { id: 'n7', type: 'noise_schedule', name: 'Cosine Sched', x: 990, y: 140, params: { schedule: 'cosine', T: 1000, beta_min: 0.0001, beta_max: 0.02 } },
      { id: 'n8', type: 'linear', name: 'Token Projection', x: 1190, y: 140, params: { in_features: 256, out_features: 16384, bias: false } },
      { id: 'n9', type: 'output', name: 'Image Tokens', x: 1390, y: 140, params: { dims: [1, 1024, 16384] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n4' },
      { id: 'c2', from: 'n2', to: 'n5' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-midjourney',
    name: 'Midjourney v6',
    family: 'diffusion',
    description: 'MJ v6 backbone, 2.5B UNet with progressive 128→1024 resolution, 4-stage cascaded generation — ~2.5B total params',
    tags: ['midjourney', 'progressive', 'cascaded', 'unet'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Noise 128x128', x: 50, y: 140, params: { dims: [1, 3, 128, 128] } },
      { id: 'n2', type: 'text_encoder', name: 'CLIP Text Enc', x: 50, y: 20, params: { model: 'openai/clip-vit-large-patch14', max_length: 256, dim: 768 } },
      { id: 'n3', type: 'time_embedding', name: 'Time Embed', x: 290, y: 20, params: { dim: 1024, max_period: 10000 } },
      { id: 'n4', type: 'diffusion_unet', name: 'Stage-1 (128)', x: 290, y: 140, params: { channels: 128, depth: 2, resolution: 128, attention: false } },
      { id: 'n5', type: 'diffusion_unet', name: 'Stage-2 (256)', x: 490, y: 140, params: { channels: 256, depth: 2, resolution: 64, attention: true } },
      { id: 'n6', type: 'diffusion_unet', name: 'Stage-3 (512)', x: 690, y: 140, params: { channels: 512, depth: 2, resolution: 32, attention: true } },
      { id: 'n7', type: 'diffusion_unet', name: 'Stage-4 (1024)', x: 890, y: 140, params: { channels: 1024, depth: 2, resolution: 16, attention: true } },
      { id: 'n8', type: 'cross_attention', name: 'CLIP Cross-Attn', x: 1090, y: 80, params: { resolution: 8, heads: 16, d_head: 64, context_dim: 768 } },
      { id: 'n9', type: 'noise_schedule', name: 'Progressive Sched', x: 1090, y: 200, params: { schedule: 'scaled_linear', T: 1000, beta_start: 0.00085, beta_end: 0.012 } },
      { id: 'n10', type: 'output', name: 'Generated 1024', x: 1310, y: 140, params: { dims: [1, 3, 1024, 1024] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n4' },
      { id: 'c2', from: 'n2', to: 'n8' },
      { id: 'c3', from: 'n3', to: 'n4' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
      { id: 'c9', from: 'n9', to: 'n10' },
    ],
    defaultParams: {},
  },
  {
    id: 'tpl-flux',
    name: 'FLUX.1',
    family: 'diffusion',
    description: 'FLUX.1 transformer-based diffusion 12B, MM-DiT (Mixture-of-Experts Diffusion Transformer) blocks, 1024×1024 — ~12B total params',
    tags: ['flux', 'mmdit', 'transformer', 'moE', 'flow-matching'],
    nodes: [
      { id: 'n1', type: 'input', name: 'Latent Noise', x: 50, y: 140, params: { dims: [1, 16, 64, 64] } },
      { id: 'n2', type: 'text_encoder', name: 'T5-XXL Enc', x: 50, y: 20, params: { model: 't5-11b', max_length: 512, dim: 4096, encoder_only: true } },
      { id: 'n3', type: 'text_encoder', name: 'CLIP-L/14', x: 290, y: 20, params: { model: 'openai/clip-vit-large-patch14', max_length: 77, dim: 768 } },
      { id: 'n4', type: 'time_embedding', name: 'Flow Timestep', x: 530, y: 20, params: { dim: 3072, max_period: 10000 } },
      { id: 'n5', type: 'layer_stack', name: 'MM-DiT-Blocks ×24', x: 310, y: 140, params: { num_layers: 24, hidden_dim: 3072, heads: 24, d_head: 128, moe_experts: 8, moe_top_k: 2 } },
      { id: 'n6', type: 'cross_attention', name: 'Dual Cross-Attn', x: 570, y: 140, params: { resolution: 8, heads: 24, d_head: 128, context_dim: [4096, 768] } },
      { id: 'n7', type: 'layer_stack', name: 'Post-Attn Blk ×8', x: 830, y: 140, params: { num_layers: 8, hidden_dim: 3072, heads: 24, d_head: 128, moe_experts: 8, moe_top_k: 2 } },
      { id: 'n8', type: 'noise_schedule', name: 'Flow Matching', x: 1090, y: 140, params: { schedule: 'flow_matching', T: 1000, sigma_min: 0.0001, sigma_max: 1.0 } },
      { id: 'n9', type: 'linear', name: 'Patch Unembed', x: 1310, y: 140, params: { in_features: 3072, out_features: 16, bias: false } },
      { id: 'n10', type: 'output', name: 'Denoised Latent', x: 1510, y: 140, params: { dims: [1, 16, 64, 64] } },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n5' },
      { id: 'c2', from: 'n2', to: 'n6' },
      { id: 'c3', from: 'n3', to: 'n6' },
      { id: 'c4', from: 'n4', to: 'n5' },
      { id: 'c5', from: 'n5', to: 'n6' },
      { id: 'c6', from: 'n6', to: 'n7' },
      { id: 'c7', from: 'n7', to: 'n8' },
      { id: 'c8', from: 'n8', to: 'n9' },
      { id: 'c9', from: 'n9', to: 'n10' },
    ],
    defaultParams: {},
  },
