[book]
title = "NEURAX — Design, Simulate, Optimize"
description = "NEURAX — An environment to design, simulate, and optimize neural architectures"
authors = ["Fossouo"]
language = "en"

[output.html]
git-repository-url = "https://github.com/rustnew/NEURAX"
edit-url-template = "https://github.com/rustnew/NEURAX/edit/main/book/src/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]
default-theme = "light"
preferred-dark-theme = "light"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
